services:
  web:
    build: .
    command: python -m uvicorn app.main:app --host 0.0.0.0 --reload
    volumes: 
      - .:/app 
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/code_review
      - SECRET_KEY=Spereira05
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db 

    
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=code_review
    ports:
      - "5433:5433"

volumes:
  postgres_data:
      
